// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL ="https://cwrijysuvpvugaexzugd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cmlqeXN1dnB2dWdhZXh6dWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTA2NTksImV4cCI6MjA3NDUyNjY2MH0.p-kTx1fB-1KkcUqS8jJ3pGuTH8mfAmVUWyVVaQ7rOPE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
