// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ikpwghvdyukujsilrtrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrcHdnaHZkeXVrdWpzaWxydHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMjI1NzYsImV4cCI6MjA4NjY5ODU3Nn0.W-rAYG5emfXzn0Sb3MAIDsndyYf_0UPv8BUV0CG8-Dg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);